import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
      <title>THT Rushbook</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="favicon.png" />
      </Head>
      <div>
        <h1>THT Rushbook</h1>
      </div>

    </div>
    
  )
}
