// Import the necessary modules and components
import Head from 'next/head';
import greek from '../public/greek.jpeg';

export default function Home() {
  return (
    <div className="relative h-screen flex items-center justify-center overflow-hidden">
      <Head>
        <title>The Rushbook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      {/* Fading Background Image */}
      <div
        className="absolute inset-0 w-full h-full"
        style={{
          backgroundImage: `linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.1)), url(${greek.src})`,
          backgroundSize: 'cover',
          backgroundRepeat: 'no-repeat',
          backgroundPosition: 'center',
        }}
      />

      <div className="relative z-10 text-center">
        <h1 className="text-6xl lg:text-8xl font-bold text-white py-2">
          The Rushbook
        </h1>
      </div>
    </div>
  );
}
