// Import the necessary modules and components
import Head from 'next/head';
import { useEffect, useState } from 'react';
import Router from 'next/router';
import supabase from '../supabase.js';
import RusheeTile from '../components/RusheeTile';

interface Rushee {
  Rushee_Uniquename: string;
  Rushee_Name: string;
  Bio: string;
  Likes: string[];
  Comments: string[];
  Dislikes: string[];
  imageUrl: string;
}

export default function Home() {
  const [book, setBook] = useState<Rushee[]>([]);
  const [userEmail, setUserEmail] = useState('');
  const [isBrother, setIsBrother] = useState(false);
  const [isAdmin, setIsAdmin] = useState('');

  useEffect(() => {
    // Fetch the rushees info from the database
    const fetchBook = async () => {
      const { data, error } = await supabase.from('book').select('*');
      if (error) {
        console.log(error);
      } else {
        console.log(data);
        setBook(data || []);
      }
    };
    fetchBook();
  }, []);

  useEffect(() => {
    // Trigger getRusheeImages function when the book is updated
    if (book.length > 0) {
      getRusheeImages();
    }
  }, [book]);

  const getRusheeImages = async () => {
    // Get the rushee images from the storage
    const updatedBook = await Promise.all(
      book.map(async (rushee) => {
        if (rushee.imageUrl) {
          return rushee;
        } else {
          const { data: ImageData, error } = await supabase
            .storage
            .from('rushee')
            .download(rushee.Rushee_Uniquename);
          if (error) {
            console.log(error);
            return rushee;
          } else {
            const blob = new Blob([ImageData as BlobPart], { type: 'image/jpeg' });
            const imageUrl = URL.createObjectURL(blob);
            return { ...rushee, imageUrl };
          }
        }
      })
    );
    setBook(updatedBook);
  };

  useEffect(() => {
    const fetchSession = async () => {
      try {
        const session = await supabase.auth.getSession();
        if (session) {
          console.log(session)
          setUserEmail(session.data.session?.user.email || '')
        }
      } catch (error) {
        console.log(error);
      }
    };

    fetchSession();
    // Listen for changes in the authentication state
    const authListener = supabase.auth.onAuthStateChange((event, session) => {
      if (event === 'SIGNED_IN' && session) {
        setUserEmail(session.user?.email || '');
      }
    });
  }, []);

  useEffect(() => {
    // Check if the user is a brother
    const checkStatus = async () => {
      const { data, error } = await supabase.from('emails').select('*').eq('email', userEmail);
      if (error) {
        console.log(error);
      } else {
        console.log(data);
        if (data.length > 0) {
          setIsBrother(true);
          setIsAdmin(data[0].Role);
        }
      }
    };
    checkStatus();
  }, [userEmail]);

  const handleGoogleSignIn = async () => {
    // Handle the Google sign in
    const { data, error } = await supabase.auth.signInWithOAuth({ provider: 'google' });
    console.log('here');
    console.log(data);
    console.log(error);
  };

  const handleGoogleSignOut = async () => {
    // Handle the Google sign out
    const { error } = await supabase.auth.signOut();
    console.log(error);
    setIsBrother(false);
  };

  const handleAddRushee = async () => {
    // Handle the add rushee button
    Router.push('/AddRushee');
  };

  const handleJoin = async () => {
    // Handle the join button
    window.open('https://thetatau-umich.org')
  };

  return (
    <div>
      <Head>
        <title>THT Rushbook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.png" />
      </Head>
      <div className='flex flex-col items-center p-2'>
        <h1 className='text-6xl lg:text-8xl font-bold bg-gradient-to-r from-amber-400 via-orange-800 to-red-950 bg-clip-text text-transparent py-2 text-center'>THT Rushbook</h1>
        {isBrother && (
          <div className='flex flex-col items-center'>
            <h2 className='text-2xl font-bold'>Welcome {userEmail}!</h2>
            <button className='bg-gradient-to-r from-amber-400 via-orange-800 to-red-950 text-white m-2 p-2 rounded-lg hover:scale-105 shadow-lg' onClick={handleGoogleSignOut}>Sign out</button>
          </div>
        ) }
      </div>
      <hr className='h-1 mx-auto border-0 rounded bg-gradient-to-r from-amber-400 via-orange-800 to-red-950' />
      {isBrother ? 
        (
          <div>
            <div className='flex flex-col items-center p-8'>
              <h1 className='text-xl font-bold pb-4 text-center'>Here are all our Rushees! Please leave your thoughts!</h1>
              {isAdmin === 'admin' ? (
                <div className='flex flex-col items-center'>
                  <h1 className='font-bold'>You are an admin</h1>
                  <button className='bg-gradient-to-r from-amber-400 via-orange-800 to-red-950 text-white m-2 p-2 rounded-lg hover:scale-105 shadow-lg' onClick={handleAddRushee}>Add Rushee</button>
                </div>
              ) : (
                <h1>You are not an admin!!!</h1>
              )}
            </div>
            <div className='grid grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4 gap-8 pt-4'>
              {book.map((rushee) => (
                  <RusheeTile
                  key={rushee.Rushee_Uniquename}
                  Rushee_Uniquename={rushee.Rushee_Uniquename}
                  Rushee_Name={rushee.Rushee_Name}
                  Bio={rushee.Bio}
                  Likes={rushee.Likes}
                  Comments={rushee.Comments}
                  Dislikes={rushee.Dislikes}
                  imageUrl={rushee.imageUrl}
                  Big={false}
                  userEmail={userEmail}
                  />
              ))}
            </div>
          </div>
        )
      :
      (
        <div className='flex flex-col items-center p-8'>
          <h1 className='text-xl font-bold pb-4 text-center'>This is for Theta Tau Brothers only!</h1>
          <button onClick={handleJoin} className='bg-gradient-to-r from-amber-400 via-orange-800 to-red-950 text-white m-2 p-2 rounded-lg hover:scale-105 shadow-lg'>Join Us!</button>
          <button className='bg-gradient-to-r from-amber-400 via-orange-800 to-red-950 text-white m-2 p-2 rounded-lg hover:scale-105 shadow-lg' onClick={handleGoogleSignIn}>Sign in with Google</button>
        </div>
      )
      }
    </div>
  );
}
